using Microsoft.EntityFrameworkCore;
using MilLib.Core.Data;
using MilLib.Core.Licensing;

// Licensing.
//
// Two programs have to agree about this exactly: the vendor's Licence Manager
// mints a key, and this re-derives it. A unit may already hold a key issued
// against the web application on the same machine, and it has to go on working
// here — so the first and most important thing checked is that this produces
// character-for-character what the PHP produces. The expected keys below were
// generated by running the PHP generator itself, not by running this code and
// writing down what came out.
//
// After that: what the four states are, when each begins, and the two ways a
// licence check can be wrong in a way that matters — letting an unlicensed
// copy run, and locking a unit out of a library it has paid for.
//
// Works on a scratch copy, deleted afterwards.
//
//   D:\dotnet10\dotnet.exe run --project tools\MilLib.LicenceProof

// The salt is the licensing secret and is not kept in committed source. The
// vendor sets MILLIB_LICENCE_SALT to run the full suite; without it the checks
// that need the real value (the ones proving these keys match the web
// application's, character for character) are skipped rather than run against a
// stand-in, since a stand-in would fail them for the wrong reason.
var Salt = Environment.GetEnvironmentVariable("MILLIB_LICENCE_SALT");

if (string.IsNullOrWhiteSpace(Salt))
{
    // Every check here is about real keys minted with the real salt, so there
    // is nothing this can prove without it. The vendor sets the variable; a
    // public clone that has not been given the secret is told so plainly rather
    // than shown a wall of failures for the wrong reason.
    Console.WriteLine("Licensing checks need the real salt.");
    Console.WriteLine("Set MILLIB_LICENCE_SALT to the vendor salt and run again.");
    return 0;
}

var real = args.Length > 0
    ? args[0]
    : Path.Combine(AppContext.BaseDirectory, "..", "..", "..", "..", "..", "app", "data", "database.sqlite");

real = Path.GetFullPath(real);

if (!File.Exists(real))
{
    Console.Error.WriteLine($"There is no file at {real}.");
    return 1;
}

var scratch = Path.Combine(Path.GetTempPath(), "mil-lib-licence-proof.sqlite");

Sweep();
File.Copy(real, scratch);

Console.WriteLine($"A scratch copy of {real}");

var failures = 0;

void Check(string what, bool ok, string saw)
{
    Console.WriteLine($"  {(ok ? "ok  " : "FAIL")}  {what,-56}  {saw}");

    if (!ok)
    {
        failures++;
    }
}

void Heading(string text)
{
    Console.WriteLine();
    Console.WriteLine(text);
}

MilLibDbContext Open() => new(DatabaseSource.File(scratch));

var today = new DateOnly(2026, 8, 20);

// ------------------------------------------ the same keys as the PHP --

Heading("The same keys the web application makes");
{
    // Produced by running the PHP generator on these inputs. If this section
    // ever fails, keys already in customers' hands have stopped working.
    (string Hardware, DateOnly? Expires, string Expected)[] known =
    [
        ("A1B2-C3D4-E5F6-0789", null, "T9FYT-ZMGXM-R4ABV-E9ETV-X9L4Z-999999"),
        ("A1B2-C3D4-E5F6-0789", new DateOnly(2027, 12, 31), "8ZPCM-GJLSM-8TBX7-SAYHA-HNG53-271231"),
        ("0000-0000-0000-0000", new DateOnly(2026, 4, 1), "TJZEQ-J8X39-F93ZD-2HMJH-TQFEH-260401"),
        ("FFFF-EEEE-DDDD-CCCC", new DateOnly(2099, 12, 31), "RHL3W-ENHSC-4BKU6-EANAN-Q94MP-999999"),
    ];

    foreach (var (hardware, expires, expected) in known)
    {
        var made = LicenceKey.Generate(hardware, Salt, expires);

        Check($"{hardware} expiring {expires?.ToString("yyyy-MM-dd") ?? "never"}",
            made == expected, made);
    }

    // The 2099 case above is the one worth naming: it is a real date, and both
    // programs have to agree that it means perpetual rather than 991231.
    Check("a date in 2099 is perpetual on both sides",
        LicenceKey.EncodeTag(new DateOnly(2099, 6, 1)) == "999999", "999999");

    Check("and the older format with no expiry at all still matches",
        LicenceKey.GenerateLegacy("A1B2-C3D4-E5F6-0789", Salt) == "ZTXGK-7KYKM-EK6MT-WMTB4-RGKAJ",
        LicenceKey.GenerateLegacy("A1B2-C3D4-E5F6-0789", Salt));
}

Heading("Reading a key");
{
    const string key = "8ZPCM-GJLSM-8TBX7-SAYHA-HNG53-271231";

    var parsed = LicenceKey.Parse(key);

    Check("the expiry comes off the key", parsed?.Expires == new DateOnly(2027, 12, 31),
        parsed?.Expires?.ToString("yyyy-MM-dd") ?? "(nothing)");

    Check("and a perpetual key says so",
        LicenceKey.Parse("T9FYT-ZMGXM-R4ABV-E9ETV-X9L4Z-999999")?.Perpetual == true, "perpetual");

    // Keys arrive read off a printed certificate, pasted out of a message, or
    // typed with the dashes somewhere else. All of those are the same key.
    foreach (var typed in new[]
    {
        "8zpcm-gjlsm-8tbx7-sayha-hng53-271231",
        "8ZPCM GJLSM 8TBX7 SAYHA HNG53 271231",
        "8ZPCMGJLSM8TBX7SAYHAHNG53271231",
        "  8ZPCM-GJLSM-8TBX7-SAYHA-HNG53-271231  ",
    })
    {
        Check($"\"{typed.Trim()[..12]}…\" is the same key",
            LicenceKey.Verify(typed, "A1B2-C3D4-E5F6-0789", Salt), "accepted");
    }

    Check("and it is tidied back into the printed form",
        LicenceKey.Tidy("8zpcm gjlsm 8tbx7 sayha hng53 271231") == key, LicenceKey.Tidy(key));
}

Heading("What a key will not do");
{
    const string key = "8ZPCM-GJLSM-8TBX7-SAYHA-HNG53-271231";

    // The whole point of the scheme. The key is for one machine.
    Check("a key for one machine does not licence another",
        !LicenceKey.Verify(key, "0000-0000-0000-0000", Salt), "refused");

    // The expiry is inside the hash, not merely appended to it, so editing the
    // date on a key changes what the key should have been.
    Check("the date on a key cannot be edited",
        !LicenceKey.Verify("8ZPCM-GJLSM-8TBX7-SAYHA-HNG53-991231", "A1B2-C3D4-E5F6-0789", Salt),
        "refused");

    Check("nor can a character in the middle of it",
        !LicenceKey.Verify("8ZPCM-GJLSM-8TBX7-SAYHA-HNG54-271231", "A1B2-C3D4-E5F6-0789", Salt),
        "refused");

    // Without the salt nobody can mint one, which is what makes it a licence
    // rather than a checksum.
    Check("and a key minted with the wrong salt is not a key",
        !LicenceKey.Verify(
            LicenceKey.Generate("A1B2-C3D4-E5F6-0789", "not the salt", new DateOnly(2027, 12, 31)),
            "A1B2-C3D4-E5F6-0789", Salt),
        "refused");

    Check("something that is not a key at all is simply refused",
        !LicenceKey.Verify("hello", "A1B2-C3D4-E5F6-0789", Salt), "refused");
}

// --------------------------------------------------- the four states --

Heading("A new installation");
{
    await using var db = Open();

    await db.LicenseInfo.ExecuteDeleteAsync();

    var licence = new Licence(db, "A1B2-C3D4-E5F6-0789", Salt);

    var standing = await licence.StandingAsync(today);

    Check("starts its trial the first time it is asked",
        standing.State == LicenceState.Trial, standing.Headline);

    Check("with the whole trial left", standing.DaysLeft == Licence.TrialDays,
        $"{standing.DaysLeft} days");

    Check("and everything works", standing.Usable, "usable");

    // The trial start is written down, so it cannot be restarted by closing
    // the application and opening it again.
    var again = await licence.StandingAsync(today.AddDays(5));

    Check("the trial does not restart when it is asked again",
        again.DaysLeft == Licence.TrialDays - 5, $"{again.DaysLeft} days");

    var last = await licence.StandingAsync(today.AddDays(Licence.TrialDays));

    Check("the last day of the trial still works",
        last is { State: LicenceState.Trial, Usable: true }, last.Headline);

    var over = await licence.StandingAsync(today.AddDays(Licence.TrialDays + 1));

    Check("and the day after it does not",
        over is { State: LicenceState.TrialOver, Usable: false }, over.Headline);

    // What it says at that point matters as much as the state. Somebody whose
    // trial has ended has not lost anything, and being told so is the
    // difference between a phone call and a panic.
    Check("but it says the records are still there",
        over.What.Contains("nothing has been lost"), "said plainly");
}

Heading("Entering a key");
{
    await using var db = Open();

    const string hardware = "A1B2-C3D4-E5F6-0789";

    var licence = new Licence(db, hardware, Salt);

    var (badShape, saidShape) = await licence.ActivateAsync("ABC-123", today);

    Check("a key of the wrong length is refused before anything else",
        !badShape && saidShape.Contains("25 or 31"), saidShape);

    // The characters that are not in the alphabet are the ones people
    // mistype: O for zero, I for one. Saying so saves a support call.
    var (badChar, saidChar) = await licence.ActivateAsync(
        "OZPCM-GJLSM-8TBX7-SAYHA-HNG53-271231", today);

    Check("and a letter that never appears in a key is named",
        !badChar && saidChar.Contains("O, I, L"), "explained");

    var (wrongMachine, saidMachine) = await licence.ActivateAsync(
        LicenceKey.Generate("0000-0000-0000-0000", Salt, null), today);

    Check("a genuine key for another machine says exactly that",
        !wrongMachine && saidMachine.Contains("not for this machine"), "explained");

    var stale = LicenceKey.Generate(hardware, Salt, today.AddDays(-1));

    var (expired, saidExpired) = await licence.ActivateAsync(stale, today);

    Check("a genuine key whose date has passed is refused, and called genuine",
        !expired && saidExpired.Contains("It is genuine"), "explained");

    Check("nothing was activated by any of that",
        (await licence.StandingAsync(today)).State != LicenceState.Licensed, "still on trial");

    var good = LicenceKey.Generate(hardware, Salt, new DateOnly(2027, 12, 31));

    var (ok, said) = await licence.ActivateAsync(good, today);

    Check("a good key activates", ok, said);

    var standing = await licence.StandingAsync(today);

    Check("and the installation is licensed",
        standing is { State: LicenceState.Licensed, Usable: true }, standing.Headline);

    Check("until the date on the key", standing.Expires == new DateOnly(2027, 12, 31),
        standing.Expires?.ToString("dd MMM yyyy") ?? "(none)");

    // Valid through the whole of the last day. A licence that dies at midnight
    // on the morning of the date printed on it expires a day early as far as
    // anybody reading the certificate is concerned.
    var lastDay = await licence.StandingAsync(new DateOnly(2027, 12, 31));

    Check("through the whole of the last day",
        lastDay is { State: LicenceState.Licensed, Usable: true }, lastDay.Headline);

    var dayAfter = await licence.StandingAsync(new DateOnly(2028, 1, 1));

    Check("and not the day after",
        dayAfter is { State: LicenceState.Expired, Usable: false }, dayAfter.Headline);

    Check("an expired licence also says the records are still there",
        dayAfter.What.Contains("still here"), "said plainly");
}

Heading("What is stored, and what it is worth");
{
    await using var db = Open();

    const string hardware = "A1B2-C3D4-E5F6-0789";

    var row = await db.LicenseInfo.AsNoTracking()
        .FirstAsync(l => l.HardwareId == hardware);

    Check("the key is written down in its printed form",
        row.LicenseKey == LicenceKey.Tidy(row.LicenseKey!), row.LicenseKey!);

    Check("with what it is and when it was entered",
        row.IsActive && row.ActivatedAt is not null && row.AppName == Vendor.Product,
        $"{row.AppName} {row.AppVersion}");

    // The row is not taken at its word. This is what stops somebody copying a
    // licensed installation's database onto another machine — the key is
    // re-derived against the machine asking, every time.
    var elsewhere = new Licence(db, "9999-8888-7777-6666", Salt);

    var copied = await elsewhere.StandingAsync(today);

    Check("that row does not licence a different machine",
        copied.State != LicenceState.Licensed, copied.Headline);

    // Nor does editing the row by hand, which is the other obvious try.
    await db.LicenseInfo
        .Where(l => l.HardwareId == hardware)
        .ExecuteUpdateAsync(s => s
            .SetProperty(l => l.LicenseKey, "AAAAA-AAAAA-AAAAA-AAAAA-AAAAA-999999")
            .SetProperty(l => l.IsActive, true)
            .SetProperty(l => l.ExpiresAt, (DateTime?)null));

    var forged = await new Licence(db, hardware, Salt).StandingAsync(today);

    Check("nor does writing a made-up key straight into the table",
        forged.State != LicenceState.Licensed, forged.Headline);

    // And having refused it, the installation falls back to its trial rather
    // than to nothing — the trial is still the trial it started with.
    Check("it falls back to the trial it already started",
        forged.State is LicenceState.Trial or LicenceState.TrialOver, forged.Headline);
}

Heading("What the screens will say");
{
    await using var db = Open();

    await db.LicenseInfo.ExecuteDeleteAsync();

    var licence = new Licence(db, "A1B2-C3D4-E5F6-0789", Salt);

    var trial = await licence.StandingAsync(today);

    // A trial always says so — somebody has to know it will stop.
    Check("a trial is always worth a banner", trial.WorthSaying, trial.Headline);

    var (_, _) = await licence.ActivateAsync(
        LicenceKey.Generate("A1B2-C3D4-E5F6-0789", Salt, null), today);

    var perpetual = await licence.StandingAsync(today);

    // A perpetual licence never needs a banner. One that appears every day
    // becomes part of the furniture and stops being read.
    Check("a perpetual licence is not", !perpetual.WorthSaying, perpetual.Headline);

    Check("and does not pretend to have a date",
        perpetual.Perpetual && perpetual.Expires is null, perpetual.Headline);

    await db.LicenseInfo.ExecuteDeleteAsync();

    var timed = new Licence(db, "A1B2-C3D4-E5F6-0789", Salt);

    await timed.ActivateAsync(
        LicenceKey.Generate("A1B2-C3D4-E5F6-0789", Salt, today.AddDays(40)), today);

    Check("nor does a licence with forty days left", !(await timed.StandingAsync(today)).WorthSaying,
        (await timed.StandingAsync(today)).Headline);

    var soon = await timed.StandingAsync(today.AddDays(20));

    Check("but one with twenty does", soon.WorthSaying, soon.Headline);

    var urgent = await timed.StandingAsync(today.AddDays(36));

    Check("and one with four days is grave", urgent.Grave, urgent.Headline);
}

Console.WriteLine();

if (failures == 0)
{
    Console.WriteLine("The keys are the same keys, they are for one machine only, "
        + "and nothing here locks a unit out of records it already has.");
}
else
{
    Console.WriteLine($"{failures} of these did not.");
}

Sweep();

return failures == 0 ? 0 : 1;

void Sweep()
{
    Microsoft.Data.Sqlite.SqliteConnection.ClearAllPools();

    foreach (var leftover in new[] { scratch, scratch + "-wal", scratch + "-shm" })
    {
        try
        {
            if (File.Exists(leftover))
            {
                File.Delete(leftover);
            }
        }
        catch (IOException)
        {
        }
    }
}
